name: teaching-biopython
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::biopython=1.78
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2
  - bioconda::fastqc=0.11.8
  - bioconda::multiqc=1.7
  - bioconda::lofreq=2.1.3.1
  - bioconda::bowtie=1.2.3
  - bioconda::bwa=0.7.17
  - bioconda::spades=3.14.0
  - conda-forge::pandoc=2.9.2.1
  - r::r=3.6.0
  - r::r-tidyverse=1.2.1
  - r::r-pander=0.6.3
  - r::r-rmarkdown=1.12
  - r::r-knitr=1.22
  - bioconda::t_coffee=11.0.8
  - bioconda::snpeff=4.5covid19
  - bioconda::clustalo=1.2.4
