name: teaching-biopython
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::biopython
  - conda-forge::markdown
  - conda-forge::pymdown-extensions
  - conda-forge::pygments
  - bioconda::fastqc
  - bioconda::multiqc
  - bioconda::lofreq
  - bioconda::bwa
  - bioconda::spades
  - conda-forge::pandoc
  - r::r=3.6.0
  - r::r-tidyverse
  - r::r-pander
  - r::r-rmarkdown
  - r::r-knitr
  - bioconda::t_coffee
  - bioconda::snpeff=4.5covid19
  - bioconda::clustalo
